INVESTOR_CITIES = [
    {
        "id": 1,
        "name_ar": "الرياض",
        "name_en": "Riyadh",
        "slug": "riyadh",
        "desc_ar": "عاصمة المملكة العربية السعودية ومركز الثقل الاقتصادي، تحتضن كبرى مشاريع رؤية 2030 وتتصدر خارطة الاستثمار في المنطقة.",
        "desc_en": "The capital of Saudi Arabia and the economic powerhouse, home to the largest Vision 2030 projects and leading the investment map in the region.",
        "image": "cities/riyadh.jpg",
        "projects_count": 3,
        "projects": [
            {
                "id": 1,
                "name_ar": "قدية — مدينة الترفيه",
                "name_en": "Qiddiya — Entertainment City",
                "company_ar": "شركة قدية للاستثمار",
                "company_en": "Qiddiya Investment Company",
                "completion": 40,
                "expected_date_ar": "2026",
                "expected_date_en": "2026",
                "location_ar": "جنوب غرب الرياض",
                "location_en": "Southwest of Riyadh",
                "desc_ar": "مدينة ترفيه عالمية تمتد على مساحة 367 كيلومتراً مربعاً، ستضم حدائق ترفيهية، ملاعب رياضية، استوديوهات إبداعية، ومرافق سياحية متكاملة. تهدف إلى أن تكون الوجهة الترفيهية الأولى في الشرق الأوسط.",
                "desc_en": "A world-class entertainment city spanning 367 square kilometers, set to include theme parks, sports venues, creative studios, and integrated tourism facilities. Aims to become the leading entertainment destination in the Middle East.",
            },
            {
                "id": 2,
                "name_ar": "مشروع درعية — البوابة",
                "name_en": "Diriyah Gate Project",
                "company_ar": "هيئة تطوير بوابة الدرعية",
                "company_en": "Diriyah Gate Development Authority",
                "completion": 60,
                "expected_date_ar": "2027",
                "expected_date_en": "2027",
                "location_ar": "شمال غرب الرياض",
                "location_en": "Northwest of Riyadh",
                "desc_ar": "مشروع تطوير تاريخي وثقافي ضخم حول منطقة الدرعية المدرجة على قائمة اليونسكو، يهدف إلى تحويلها إلى وجهة سياحية وثقافية عالمية تجمع التراث النجدي الأصيل بالمرافق السياحية الحديثة.",
                "desc_en": "A massive historical and cultural development project around the UNESCO-listed Diriyah area, aiming to transform it into a global cultural and tourism destination that combines authentic Najdi heritage with modern tourist facilities.",
            },
            {
                "id": 3,
                "name_ar": "المربع الجديد",
                "name_en": "New Murabba",
                "company_ar": "شركة المربع الجديد للتطوير",
                "company_en": "New Murabba Development Company",
                "completion": 15,
                "expected_date_ar": "2030",
                "expected_date_en": "2030",
                "location_ar": "وسط الرياض",
                "location_en": "Central Riyadh",
                "desc_ar": "مشروع حضري مستقبلي يُعدّ من أضخم مشاريع التطوير الحضري في العالم، يتمحور حول ناطحة سحاب مبتكرة بتصميم مكعب ضخم. سيضم وحدات سكنية وتجارية وترفيهية وفندقية في قلب الرياض.",
                "desc_en": "A futuristic urban project considered one of the largest urban development projects in the world, centered around an innovative skyscraper with a massive cube design. It will include residential, commercial, entertainment, and hotel units in the heart of Riyadh.",
            },
        ],
    },
    {
        "id": 2,
        "name_ar": "جدة",
        "name_en": "Jeddah",
        "slug": "jeddah",
        "desc_ar": "البوابة الاقتصادية للمملكة على البحر الأحمر، تشهد نهضة عمرانية واستثمارية غير مسبوقة تجعلها وجهة رئيسية لكبار المستثمرين.",
        "desc_en": "The Kingdom's economic gateway on the Red Sea, witnessing an unprecedented construction and investment boom that makes it a prime destination for major investors.",
        "image": "cities/jeddah.jpg",
        "projects_count": 3,
        "projects": [
            {
                "id": 1,
                "name_ar": "برج جدة",
                "name_en": "Jeddah Tower",
                "company_ar": "شركة جدة الاقتصادية",
                "company_en": "Jeddah Economic Company",
                "completion": 80,
                "expected_date_ar": "2025",
                "expected_date_en": "2025",
                "location_ar": "شمال جدة — حي الشاطئ",
                "location_en": "North Jeddah — Al Shati District",
                "desc_ar": "أعلى برج في العالم عند اكتماله، يتجاوز ارتفاعه الكيلومتر الواحد. يضم فندقاً فاخراً، شققاً سكنية، مكاتب تجارية، ومركزاً تجارياً. سيكون رمزاً عالمياً للطموح السعودي ووجهة سياحية واستثمارية استثنائية.",
                "desc_en": "The tallest tower in the world upon completion, exceeding one kilometer in height. It will include a luxury hotel, residential apartments, commercial offices, and a shopping center. It will be a global symbol of Saudi ambition and an exceptional tourist and investment destination.",
            },
            {
                "id": 2,
                "name_ar": "تطوير كورنيش جدة",
                "name_en": "Jeddah Corniche Development",
                "company_ar": "هيئة تطوير جدة",
                "company_en": "Jeddah Development Authority",
                "completion": 70,
                "expected_date_ar": "2025",
                "expected_date_en": "2025",
                "location_ar": "الواجهة البحرية لجدة",
                "location_en": "Jeddah Seafront",
                "desc_ar": "مشروع تطوير شامل للواجهة البحرية لجدة يمتد على طول الكورنيش، يشمل تطوير المشاة والمرافق الترفيهية والمطاعم والمساحات العامة لتحويل الكورنيش إلى وجهة سياحية وترفيهية متكاملة.",
                "desc_en": "A comprehensive development project for Jeddah's seafront along the corniche, including pedestrian development, entertainment facilities, restaurants, and public spaces to transform the corniche into an integrated tourism and entertainment destination.",
            },
            {
                "id": 3,
                "name_ar": "مشروع البحر الأحمر",
                "name_en": "Red Sea Project",
                "company_ar": "شركة البحر الأحمر العالمية",
                "company_en": "Red Sea Global",
                "completion": 55,
                "expected_date_ar": "2030",
                "expected_date_en": "2030",
                "location_ar": "الساحل الغربي للمملكة",
                "location_en": "Western Coast of Saudi Arabia",
                "desc_ar": "وجهة سياحية فاخرة مستدامة تمتد على أكثر من 28,000 كيلومتر مربع على ساحل البحر الأحمر، تضم جزراً وشعاباً مرجانية وبراكين خامدة وغابات مانغروف. تستهدف استقطاب مليون زائر سنوياً.",
                "desc_en": "A sustainable luxury tourism destination spanning over 28,000 square kilometers on the Red Sea coast, featuring islands, coral reefs, dormant volcanoes, and mangrove forests. Targeting one million visitors annually.",
            },
        ],
    },
    {
        "id": 3,
        "name_ar": "العُلا",
        "name_en": "AlUla",
        "slug": "alula",
        "desc_ar": "وجهة استثمارية صاعدة في قطاع السياحة والتراث، تشهد تحولاً استثمارياً ضخماً بدعم مباشر من الحكومة السعودية.",
        "desc_en": "A rising investment destination in the tourism and heritage sector, witnessing a massive investment transformation with direct support from the Saudi government.",
        "image": "cities/alula.jpg",
        "projects_count": 2,
        "projects": [
            {
                "id": 1,
                "name_ar": "تطوير العُلا السياحي",
                "name_en": "AlUla Tourism Development",
                "company_ar": "الهيئة الملكية لمحافظة العُلا",
                "company_en": "Royal Commission for AlUla",
                "completion": 50,
                "expected_date_ar": "2035",
                "expected_date_en": "2035",
                "location_ar": "محافظة العُلا — منطقة المدينة المنورة",
                "location_en": "AlUla Governorate — Madinah Region",
                "desc_ar": "مشروع تطوير سياحي شامل يهدف إلى تحويل العُلا إلى وجهة سياحية عالمية تستقطب مليوني زائر سنوياً بحلول 2035، مع الحفاظ على التراث الطبيعي والثقافي للمنطقة وتطوير البنية التحتية السياحية بالكامل.",
                "desc_en": "A comprehensive tourism development project aiming to transform AlUla into a global tourist destination attracting two million visitors annually by 2035, while preserving the natural and cultural heritage of the area and fully developing tourist infrastructure.",
            },
            {
                "id": 2,
                "name_ar": "منتجع شرعان",
                "name_en": "Sharaan Resort",
                "company_ar": "شركة AWJ للاستثمارات",
                "company_en": "AWJ Investments",
                "completion": 65,
                "expected_date_ar": "2026",
                "expected_date_en": "2026",
                "location_ar": "محمية شرعان الطبيعية — العُلا",
                "location_en": "Sharaan Nature Reserve — AlUla",
                "desc_ar": "منتجع فاخر فريد من نوعه منحوت داخل الجبال الصخرية لمحمية شرعان الطبيعية، صممه المعماري العالمي جان نوفيل. سيضم 40 جناحاً فاخراً، مطاعم راقية، ومرافق سبا وصحة داخل تكوينات صخرية طبيعية.",
                "desc_en": "A unique luxury resort carved inside the rocky mountains of Sharaan Nature Reserve, designed by world-renowned architect Jean Nouvel. It will feature 40 luxury suites, fine dining restaurants, and spa and wellness facilities within natural rock formations.",
            },
        ],
    },
    {
        "id": 4,
        "name_ar": "أبها",
        "name_en": "Abha",
        "slug": "abha",
        "desc_ar": "عاصمة منطقة عسير تشهد طفرة استثمارية في قطاع السياحة الجبلية، مدعومة بمشاريع رؤية 2030 الرامية إلى تطوير المنطقة وتحويلها لوجهة سياحية عالمية.",
        "desc_en": "The capital of Asir region is experiencing an investment boom in mountain tourism, supported by Vision 2030 projects aimed at developing the region and transforming it into a global tourist destination.",
        "image": "cities/abha.jpg",
        "projects_count": 3,
        "projects": [
            {
                "id": 1,
                "name_ar": "مشروع السودة للتطوير",
                "name_en": "Al Soudah Development Project",
                "company_ar": "هيئة تطوير منطقة عسير",
                "company_en": "Aseer Development Authority",
                "completion": 35,
                "expected_date_ar": "2028",
                "expected_date_en": "2028",
                "location_ar": "جبال السودة — أبها",
                "location_en": "Al Soudah Mountains — Abha",
                "desc_ar": "مشروع تطوير سياحي جبلي ضخم على أعلى قمم جبال عسير، يشمل منتجعات فاخرة، فنادق، مسارات للمشي، وتجارب طبيعية فريدة. يهدف إلى تحويل منطقة السودة إلى وجهة سياحية جبلية رائدة على مستوى العالم.",
                "desc_en": "A massive mountain tourism development project on the highest peaks of Asir mountains, including luxury resorts, hotels, hiking trails, and unique natural experiences. Aims to transform the Al Soudah area into a world-leading mountain tourism destination.",
            },
            {
                "id": 2,
                "name_ar": "منتجعات عسير الجبلية",
                "name_en": "Asir Mountain Resorts",
                "company_ar": "الهيئة السعودية للسياحة",
                "company_en": "Saudi Tourism Authority",
                "completion": 45,
                "expected_date_ar": "2027",
                "expected_date_en": "2027",
                "location_ar": "منطقة عسير — أبها",
                "location_en": "Asir Region — Abha",
                "desc_ar": "سلسلة منتجعات سياحية جبلية متكاملة تنتشر عبر أجمل مواقع منطقة عسير، تقدم تجارب إقامة فاخرة وسط الطبيعة الجبلية الخلابة مع أنشطة ترفيهية وثقافية تعكس تراث المنطقة العريق.",
                "desc_en": "A series of integrated mountain tourism resorts spread across the most beautiful locations in the Asir region, offering luxury accommodation experiences amid stunning mountain nature with recreational and cultural activities reflecting the region's rich heritage.",
            },
            {
                "id": 3,
                "name_ar": "وادي أبها",
                "name_en": "Wadi Abha",
                "company_ar": "أردارا",
                "company_en": "Ardara",
                "completion": 20,
                "expected_date_ar": "2035",
                "expected_date_en": "2035",
                "location_ar": "وادي أبها — منطقة عسير",
                "location_en": "Abha Valley — Asir Region",
                "desc_ar": "مشروع تطوير سياحي متكامل في وادي أبها يهدف إلى الاستفادة من الطبيعة الخلابة للوادي وتحويله إلى وجهة سياحية راقية، يشمل منتجعات فاخرة ومرافق ترفيهية وتجارب ثقافية أصيلة تعكس هوية المنطقة.",
                "desc_en": "An integrated tourism development project in Abha Valley aiming to leverage the valley's stunning nature and transform it into an upscale tourist destination, including luxury resorts, entertainment facilities, and authentic cultural experiences reflecting the region's identity.",
            },
        ],
    },
    {
        "id": 5,
        "name_ar": "تبوك",
        "name_en": "Tabuk",
        "slug": "tabuk",
        "desc_ar": "المدينة الأسرع نمواً استثمارياً في المملكة، تحتضن أضخم المشاريع العملاقة في تاريخ البشرية ضمن مبادرات رؤية 2030.",
        "desc_en": "The fastest-growing investment city in the Kingdom, home to the most mega-projects in human history within Vision 2030 initiatives.",
        "image": "cities/tabuk.jpg",
        "projects_count": 3,
        "projects": [
            {
                "id": 1,
                "name_ar": "نيوم — المدينة الذكية",
                "name_en": "NEOM — Smart City",
                "company_ar": "شركة نيوم",
                "company_en": "NEOM Company",
                "completion": 20,
                "expected_date_ar": "2030",
                "expected_date_en": "2030",
                "location_ar": "خليج العقبة — تبوك",
                "location_en": "Gulf of Aqaba — Tabuk",
                "desc_ar": "مدينة المستقبل الأضخم في العالم، تمتد على مساحة 26,500 كيلومتر مربع على ساحل البحر الأحمر وخليج العقبة. تعتمد بالكامل على الطاقة المتجددة وتستهدف استقطاب مليون ساكن وملايين الزوار سنوياً.",
                "desc_en": "The world's largest city of the future, spanning 26,500 square kilometers on the Red Sea coast and Gulf of Aqaba. Fully powered by renewable energy, targeting one million residents and millions of visitors annually.",
            },
            {
                "id": 2,
                "name_ar": "ذا لاين",
                "name_en": "THE LINE",
                "company_ar": "شركة نيوم",
                "company_en": "NEOM Company",
                "completion": 15,
                "expected_date_ar": "2030",
                "expected_date_en": "2030",
                "location_ar": "صحراء تبوك — نيوم",
                "location_en": "Tabuk Desert — NEOM",
                "desc_ar": "مدينة خطية ثورية بلا سيارات ولا شوارع، تمتد على طول 170 كيلومتراً بعرض 200 متر فقط وارتفاع 500 متر. ستستضيف 9 ملايين شخص وتعتمد على الذكاء الاصطناعي لإدارة جميع جوانب الحياة اليومية.",
                "desc_en": "A revolutionary linear city with no cars or streets, stretching 170 kilometers long, only 200 meters wide, and 500 meters tall. It will host 9 million people and rely on artificial intelligence to manage all aspects of daily life.",
            },
            {
                "id": 3,
                "name_ar": "تروجينا",
                "name_en": "Trojena",
                "company_ar": "شركة نيوم",
                "company_en": "NEOM Company",
                "completion": 30,
                "expected_date_ar": "2026",
                "expected_date_en": "2026",
                "location_ar": "جبال نيوم — تبوك",
                "location_en": "NEOM Mountains — Tabuk",
                "desc_ar": "وجهة سياحية جبلية فريدة ضمن مشروع نيوم، ستستضيف دورة الألعاب الآسيوية الشتوية 2029. تضم منتجعات تزلج، بحيرة اصطناعية، قرية خارجية، ومناطق جبلية خلابة على ارتفاع 1500 متر فوق مستوى البحر.",
                "desc_en": "A unique mountain tourism destination within the NEOM project, set to host the 2029 Asian Winter Games. Features ski resorts, an artificial lake, an outdoor village, and stunning mountain areas at 1,500 meters above sea level.",
            },
        ],
    },
]