TOURIST_CITIES = [
    {
        "id": 1,
        "name_ar": "الرياض",
        "name_en": "Riyadh",
        "slug": "riyadh",
        "desc_ar": "عاصمة المملكة العربية السعودية، مدينة تجمع بين الأصالة والحداثة، تزخر بالمعالم التاريخية والوجهات الترفيهية العالمية.",
        "desc_en": "The capital of Saudi Arabia, a city that blends authenticity with modernity, rich in historical landmarks and world-class entertainment destinations.",
        "image": "cities/riyadh.jpg",
        "places_count": 5,
        "places": [
            {
                "id": 1,
                "name_ar": "بوليفارد رياض سيتي",
                "name_en": "Boulevard Riyadh City",
                "type_ar": "ترفيهي",
                "type_en": "Entertainment",
                "desc_ar": "أكبر وجهة ترفيهية في الرياض، تضم مطاعم عالمية، مقاهي، عروض حية، وألعاب. مناسبة لمن يبحث عن تجربة حياة ليلية وفعاليات مستمرة خصوصاً وقت موسم الرياض.",
                "desc_en": "The largest entertainment destination in Riyadh, featuring international restaurants, cafes, live shows, and games. Perfect for those seeking a vibrant nightlife experience, especially during Riyadh Season.",
                "image": "places/boulevard.jpg",
                "recommend_months_ar": "أكتوبر — مارس",
                "recommend_months_en": "October — March",
            },
            {
                "id": 2,
                "name_ar": "برج المملكة",
                "name_en": "Kingdom Tower",
                "type_ar": "معلم حضاري",
                "type_en": "Landmark",
                "desc_ar": "أشهر برج في الرياض، يحتوي على جسر معلق يتيح إطلالة بانورامية رائعة على المدينة. مكان ممتاز للتصوير ومشاهدة الرياض من الأعلى.",
                "desc_en": "The most iconic tower in Riyadh, featuring a sky bridge that offers a stunning panoramic view of the city. An excellent spot for photography and viewing Riyadh from above.",
                "image": "places/kingdom_tower.jpg",
                "recommend_months_ar": "على مدار السنة",
                "recommend_months_en": "Year-round",
            },
            {
                "id": 3,
                "name_ar": "حافة العالم",
                "name_en": "Edge of the World",
                "type_ar": "مغامرة",
                "type_en": "Adventure",
                "desc_ar": "من أقوى التجارب الطبيعية في المملكة، عبارة عن جرف صخري شاهق بإطلالة مفتوحة لا نهاية لها على الصحراء. مثالي لعشاق المغامرة والتصوير ومشاهدة الغروب.",
                "desc_en": "One of the most powerful natural experiences in the Kingdom — a towering rocky cliff with an open, endless view of the desert. Ideal for adventure lovers, photographers, and sunset watchers.",
                "image": "places/edge_of_world.jpg",
                "recommend_months_ar": "نوفمبر — فبراير",
                "recommend_months_en": "November — February",
            },
            {
                "id": 4,
                "name_ar": "قصر المصمك",
                "name_en": "Masmak Palace",
                "type_ar": "تاريخي",
                "type_en": "Historical",
                "desc_ar": "موقع تاريخي مهم يرمز لبداية توحيد المملكة العربية السعودية. يمنحك تجربة ثقافية سريعة ومفيدة في قلب الرياض القديمة.",
                "desc_en": "An important historical site symbolizing the beginning of Saudi Arabia's unification. Offers a quick yet enriching cultural experience in the heart of old Riyadh.",
                "image": "places/masmak.jpg",
                "recommend_months_ar": "على مدار السنة",
                "recommend_months_en": "Year-round",
            },
            {
                "id": 5,
                "name_ar": "الدرعية",
                "name_en": "Diriyah",
                "type_ar": "تراثي",
                "type_en": "Heritage",
                "desc_ar": "منطقة تاريخية مدرجة على قائمة اليونسكو للتراث العالمي، تتميز بطابعها النجدي الأصيل ومطاعمها ومقاهيها الفاخرة. تجمع بين عراقة التاريخ ومتعة السياحة الحديثة.",
                "desc_en": "A UNESCO World Heritage Site with an authentic Najdi character, featuring upscale restaurants and cafes. A perfect blend of historical richness and modern tourism experience.",
                "image": "places/diriyah.jpg",
                "recommend_months_ar": "أكتوبر — أبريل",
                "recommend_months_en": "October — April",
            },
        ],
    },
    {
        "id": 2,
        "name_ar": "جدة",
        "name_en": "Jeddah",
        "slug": "jeddah",
        "desc_ar": "بوابة الحرمين الشريفين ومدينة التنوع، تطل على البحر الأحمر بكورنيشها الشهير وتاريخها العريق في جدة التاريخية.",
        "desc_en": "The Gateway to the Two Holy Mosques and a city of diversity, overlooking the Red Sea with its famous corniche and rich history in Historic Jeddah.",
        "image": "cities/jeddah.jpg",
        "places_count": 5,
        "places": [
            {
                "id": 1,
                "name_ar": "كورنيش جدة",
                "name_en": "Jeddah Corniche",
                "type_ar": "عام",
                "type_en": "General",
                "desc_ar": "ممشى ساحلي ممتد على البحر الأحمر، مثالي للمشي وركوب الدراجات والاستمتاع بجلسات الغروب الساحرة. وجهة مفضلة للعائلات والزوار طوال اليوم.",
                "desc_en": "A coastal promenade stretching along the Red Sea, perfect for walking, cycling, and enjoying magical sunset views. A favorite destination for families and visitors throughout the day.",
                "image": "places/corniche.jpg",
                "recommend_months_ar": "ديسمبر — مارس",
                "recommend_months_en": "December — March",
            },
            {
                "id": 2,
                "name_ar": "نافورة الملك فهد",
                "name_en": "King Fahd Fountain",
                "type_ar": "معلم حضاري",
                "type_en": "Landmark",
                "desc_ar": "أعلى نافورة في العالم، ترتفع إلى أكثر من 300 متر فوق سطح البحر الأحمر. منظرها مبهر خصوصاً في الليل حين تُضاء بأضواء ملونة تجعلها أيقونة جدة بلا منازع.",
                "desc_en": "The tallest fountain in the world, rising over 300 meters above the Red Sea. Its view is breathtaking, especially at night when illuminated by colorful lights, making it Jeddah's undisputed icon.",
                "image": "places/fountain.jpg",
                "recommend_months_ar": "على مدار السنة",
                "recommend_months_en": "Year-round",
            },
            {
                "id": 3,
                "name_ar": "جدة التاريخية",
                "name_en": "Historic Jeddah",
                "type_ar": "تراثي",
                "type_en": "Heritage",
                "desc_ar": "موقع مدرج على قائمة اليونسكو للتراث العالمي، يضم أزقة قديمة وبيوتاً تاريخية بنوافذها الخشبية المزخرفة التي تعكس هوية المدينة وعمق ثقافتها.",
                "desc_en": "A UNESCO World Heritage Site featuring ancient alleyways and historic houses with ornate wooden windows, reflecting the city's identity and cultural depth.",
                "image": "places/historic_jeddah.jpg",
                "recommend_months_ar": "أكتوبر — أبريل",
                "recommend_months_en": "October — April",
            },
            {
                "id": 4,
                "name_ar": "واجهة جدة البحرية",
                "name_en": "Jeddah Waterfront",
                "type_ar": "ترفيهي",
                "type_en": "Entertainment",
                "desc_ar": "منطقة حديثة ومتكاملة تطل على البحر الأحمر، تضم مساحات خضراء واسعة، ومناطق ألعاب للأطفال، وجلسات عائلية مريحة مع أجواء بحرية هادئة ومنعشة.",
                "desc_en": "A modern integrated area overlooking the Red Sea, featuring spacious green areas, children's play zones, and comfortable family seating with a calm and refreshing seaside atmosphere.",
                "image": "places/waterfront.jpg",
                "recommend_months_ar": "ديسمبر — مارس",
                "recommend_months_en": "December — March",
            },
            {
                "id": 5,
                "name_ar": "فقيه أكواريوم",
                "name_en": "Fakieh Aquarium",
                "type_ar": "ترفيهي",
                "type_en": "Entertainment",
                "desc_ar": "وجهة ترفيهية وتعليمية رائعة تتيح لك مشاهدة مئات الكائنات البحرية عن قرب، من أسماك ملونة وقروش وسلاحف بحرية. تجربة ممتعة ومثيرة للأسر والأطفال.",
                "desc_en": "A wonderful entertainment and educational destination that lets you see hundreds of marine creatures up close, including colorful fish, sharks, and sea turtles. A fun and exciting experience for families and children.",
                "image": "places/aquarium.jpg",
                "recommend_months_ar": "على مدار السنة",
                "recommend_months_en": "Year-round",
            },
        ],
    },
    {
        "id": 3,
        "name_ar": "العُلا",
        "name_en": "AlUla",
        "slug": "alula",
        "desc_ar": "وادي التاريخ والفن والطبيعة، تحتضن آثار مدائن صالح وتشكيلات صخرية فريدة تجعلها وجهة سياحية عالمية استثنائية.",
        "desc_en": "The valley of history, art, and nature, home to the ruins of Hegra and unique rock formations that make it an exceptional global tourism destination.",
        "image": "cities/alula.jpg",
        "places_count": 6,
        "places": [
            {
                "id": 1,
                "name_ar": "جبل الفيل",
                "name_en": "Elephant Rock",
                "type_ar": "طبيعي",
                "type_en": "Nature",
                "desc_ar": "تشكيل صخري طبيعي ضخم يشبه الفيل بشكل مذهل، يُعدّ من أشهر المعالم الطبيعية في العُلا. يبلغ ارتفاعه نحو 52 متراً ويحيط به مطعم مفتوح يتيح تجربة عشاء فريدة.",
                "desc_en": "A massive natural rock formation strikingly resembling an elephant, considered one of the most famous natural landmarks in AlUla. It stands about 52 meters tall and is surrounded by an open-air restaurant offering a unique dining experience.",
                "image": "places/elephant_rock.jpg",
                "recommend_months_ar": "أكتوبر — مارس",
                "recommend_months_en": "October — March",
            },
            {
                "id": 2,
                "name_ar": "قاعة المرايا",
                "name_en": "Maraya Concert Hall",
                "type_ar": "ثقافي",
                "type_en": "Cultural",
                "desc_ar": "أكبر مبنى مغطى بالمرايا في العالم مسجل في موسوعة غينيس، يعكس جمال الصحراء المحيطة به بشكل ساحر. يُستخدم لاستضافة الفعاليات والحفلات الموسيقية العالمية الكبرى.",
                "desc_en": "The world's largest mirrored building, listed in the Guinness World Records, enchantingly reflecting the surrounding desert beauty. Used to host major global events and concerts.",
                "image": "places/maraya.jpg",
                "recommend_months_ar": "أكتوبر — مارس",
                "recommend_months_en": "October — March",
            },
            {
                "id": 3,
                "name_ar": "جبل عكمة",
                "name_en": "Jabal Ikmah",
                "type_ar": "تاريخي",
                "type_en": "Historical",
                "desc_ar": "يُعرف بالمكتبة المفتوحة للعالم، إذ تزخر جدرانه الصخرية بآلاف النقوش والكتابات القديمة التي تعود لآلاف السنين. وجهة استثنائية لعشاق التاريخ وعلم الآثار.",
                "desc_en": "Known as the open library of the world, its rocky walls are adorned with thousands of ancient inscriptions and writings dating back thousands of years. An exceptional destination for history and archaeology enthusiasts.",
                "image": "places/jabal_ikmah.jpg",
                "recommend_months_ar": "نوفمبر — فبراير",
                "recommend_months_en": "November — February",
            },
            {
                "id": 4,
                "name_ar": "البلدة القديمة بالعُلا",
                "name_en": "Old Town AlUla",
                "type_ar": "تراثي",
                "type_en": "Heritage",
                "desc_ar": "قرية عريقة يعود تاريخها لأكثر من ألف عام، تضم أكثر من 900 منزل حجري قديم وأزقة ضيقة تحكي تاريخاً عميقاً. تم تطويرها بعناية لتكون وجهة سياحية تجمع الأصالة والحداثة.",
                "desc_en": "An ancient village over a thousand years old, comprising more than 900 old stone houses and narrow alleyways that tell a deep history. Carefully developed to be a tourist destination blending authenticity with modernity.",
                "image": "places/old_town_alula.jpg",
                "recommend_months_ar": "أكتوبر — أبريل",
                "recommend_months_en": "October — April",
            },
            {
                "id": 5,
                "name_ar": "وادي عشار",
                "name_en": "Ashar Valley",
                "type_ar": "مغامرة",
                "type_en": "Adventure",
                "desc_ar": "واحد من أجمل الأودية في العُلا، يتميز بمناظره الطبيعية الخلابة وتضاريسه الصخرية الفريدة. يحتضن منتجعات فاخرة وتجارب صحراوية راقية تجعل الإقامة فيه تجربة لا تُنسى.",
                "desc_en": "One of the most beautiful valleys in AlUla, characterized by its stunning natural scenery and unique rocky terrain. It hosts luxury resorts and upscale desert experiences that make staying here an unforgettable adventure.",
                "image": "places/ashar_valley.jpg",
                "recommend_months_ar": "نوفمبر — فبراير",
                "recommend_months_en": "November — February",
            },
            {
                "id": 6,
                "name_ar": "إسطبل خيل — إندلووب",
                "name_en": "Horse Stables — ENDULOOP",
                "type_ar": "ترفيهي",
                "type_en": "Entertainment",
                "desc_ar": "تجربة ركوب خيل ترفيهية فريدة ضمن فعاليات السياحة في موقع إندلووب بالعُلا. تمنحك فرصة استكشاف التضاريس الصحراوية الرائعة على ظهر الخيل بأسلوب أصيل.",
                "desc_en": "A unique recreational horse riding experience within the tourism activities at the Incense Road site in AlUla. It gives you the opportunity to explore the stunning desert terrain on horseback in an authentic style.",
                "image": "places/horse_stables.jpg",
                "recommend_months_ar": "أكتوبر — مارس",
                "recommend_months_en": "October — March",
            },
        ],
    },
    {
        "id": 4,
        "name_ar": "أبها",
        "name_en": "Abha",
        "slug": "abha",
        "desc_ar": "عروس الجبال وعاصمة منطقة عسير، تتميز بمناخها المعتدل وطبيعتها الخضراء وضبابها الرومانسي الذي يكسو جبالها طوال العام.",
        "desc_en": "The Bride of Mountains and the capital of Asir region, distinguished by its moderate climate, green nature, and romantic fog that covers its mountains throughout the year.",
        "image": "cities/abha.jpg",
        "places_count": 4,
        "places": [
            {
                "id": 1,
                "name_ar": "السودة",
                "name_en": "Al Soudah",
                "type_ar": "طبيعي",
                "type_en": "Nature",
                "desc_ar": "أعلى قمة جبلية في المملكة العربية السعودية، تقع على ارتفاع يتجاوز 3000 متر فوق مستوى البحر. تتميز بمناظرها الخلابة والضباب الكثيف الذي يحيطها، وتضم تلفريك يوفر رحلة جوية مثيرة فوق الجبال.",
                "desc_en": "The highest mountain peak in Saudi Arabia, located at an altitude exceeding 3000 meters above sea level. Known for its stunning views and thick fog, it features a cable car providing a thrilling aerial journey over the mountains.",
                "image": "places/soudah.jpg",
                "recommend_months_ar": "مارس — نوفمبر",
                "recommend_months_en": "March — November",
            },
            {
                "id": 2,
                "name_ar": "حديقة أبو خيال",
                "name_en": "Abu Khyal Park",
                "type_ar": "ترفيهي",
                "type_en": "Entertainment",
                "desc_ar": "حديقة عامة واسعة وخضراء في قلب أبها، تُعدّ من أبرز متنزهات المدينة وأكثرها زيارة. توفر بيئة طبيعية هادئة مع مساحات مفتوحة للأسر والأطفال، محاطة بأشجار كثيفة وهواء نقي منعش.",
                "desc_en": "A spacious and lush public garden in the heart of Abha, considered one of the city's most prominent and visited parks. It provides a calm natural environment with open spaces for families and children, surrounded by dense trees and fresh air.",
                "image": "places/abu_khyal.jpg",
                "recommend_months_ar": "على مدار السنة",
                "recommend_months_en": "Year-round",
            },
            {
                "id": 3,
                "name_ar": "منتزه دلغان الوطني",
                "name_en": "Dalgan National Park",
                "type_ar": "طبيعي",
                "type_en": "Nature",
                "desc_ar": "منتزه وطني يمتد على مساحة شاسعة من الطبيعة العسيرية الأصيلة، يضم غابات كثيفة ومسارات للمشي والتنزه وسط الطبيعة الجبلية. وجهة مثالية للباحثين عن الهدوء والتواصل مع الطبيعة.",
                "desc_en": "A national park stretching across a vast area of authentic Asiri nature, featuring dense forests and trails for walking and hiking amid the mountainous landscape. An ideal destination for those seeking tranquility and a connection with nature.",
                "image": "places/dalgan.jpg",
                "recommend_months_ar": "مارس — أكتوبر",
                "recommend_months_en": "March — October",
            },
            {
                "id": 4,
                "name_ar": "ممشى الضباب",
                "name_en": "The Fog Walk",
                "type_ar": "طبيعي",
                "type_en": "Nature",
                "desc_ar": "ممشى جبلي فريد من نوعه يمتد على حافة الجبال في أبها، يتيح لك التجول وسط الضباب الكثيف بإطلالات خلابة على الوادي والجبال المحيطة. تجربة رومانسية وهادئة لا مثيل لها خصوصاً في ساعات الصباح الباكر.",
                "desc_en": "A unique mountain walkway extending along the edge of Abha's mountains, allowing you to stroll through thick fog with breathtaking views of the valley and surrounding mountains. An unparalleled romantic and peaceful experience, especially in the early morning hours.",
                "image": "places/fog_walk.jpg",
                "recommend_months_ar": "على مدار السنة",
                "recommend_months_en": "Year-round",
            },
        ],
    },
]
